name: Android

on:
  push:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Import GPG key for git-secret
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes

      - name: Install git-secret
        run: sudo apt-get install git-secret

      - name: Decrypt secrets
        run: git secret reveal -f

      - name: Build and test app
        run: ./gradlew build

      - name: Deploy beta version
        if: github.ref == 'refs/heads/develop'
        run: ./gradlew publishReleaseBundle --track beta --release-status completed

      # Assumes that commits to main are always merged from develop
      - name: Promote beta to release
        if: github.ref == 'refs/heads/main'
        run: ./gradlew promoteArtifact --from-track beta --promote-track production --release-status completed

      - uses: actions/upload-artifact@v2
        with:
          name: Android artifacts
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab
