name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Import GPG key for git-secret
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes

      - name: Install git-secret
        run: sudo apt-get install git-secret

      - name: Decrypt secrets
        run: git secret reveal -f

      - name: Deploy production version
        run: ./gradlew assembleRelease publishReleaseBundle --track production --release-status completed

      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["bug", "fix"]
                },
                {
                  "title": "## 🔧 Maintenance",
                  "labels": ["chore", "maintenance"]
                },
                {
                  "title": "## ⬆️ Dependencies",
                  "labels": ["dependencies"]
                },
                {
                  "title": "## 📚 Documentation",
                  "labels": ["documentation"]
                },
                {
                  "title": "## 🧪 Tests",
                  "labels": ["test"]
                }
              ],
              "tag_resolver": {
                "method": "sort"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab

      - uses: actions/upload-artifact@v4
        with:
          name: Android artifacts
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab

  increment-version:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Increment version code
        run: sed -i 's/versionCode = [0-9]*/versionCode = '$(awk '/versionCode =/{print $3=$3+1}' app/build.gradle.kts)'/g' app/build.gradle.kts

      - name: Increment version name
        run: sed -i 's/versionName = .*/versionName = "'$(awk '/versionName =/{print substr($3,2,length($3)-2)+1}' app/build.gradle.kts)'"/g' app/build.gradle.kts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip ci] Increment version code & name for next release'
          branch: main
